name: Test and build
on:
  push:
    branches:
      - master
      - workflows
  # release:
  #   types: [published]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.8]
    steps:
      - uses: actions/checkout@v2
        name: Check out the repo
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python test/test_parsers.py
  push_to_registry:
    name: Push Docker image to GitHub Packages
    needs: test
    runs-on: ubuntu-latest
    if: ${{github.ref == 'refs/heads/workflows'}}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: evoja/docker-git-auto-deploy/git-auto-deploy
          tag_with_ref: true
