name: Test and build
on:
  push:
    branches:
      - master
      - dev*
    tags:
      - v0.*
      - dv0.*
      - dv/0.*

jobs:

  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.8]
    steps:
      - uses: actions/checkout@v2
        name: Check out the repo
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python test/test_parsers.py


  push_to_registry:
    name: Push docker images to GitHub Packages
    needs: test
    runs-on: ubuntu-latest
    env:
      IS_ROOT: ${{github.repository == 'olipo186/Git-Auto-Deploy'}}
      ROOT_REPO: 'olipo186/git-auto-deploy'
      ROOT_PREFIX: 'olipo186-'
      ROOT_TAG: 'latest'
      IMAGE_PUSH: ${{ startsWith(github.ref, 'refs/tags') || github.ref == 'refs/heads/master' || endsWith(github.ref, '-push') }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Calculate environments
        run: |
          echo IMAGE_REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo IMAGE_TAG=$(./.github/workflows/docker-tag.sh ${{github.ref}}) >> $GITHUB_ENV

      - name: Calculate root image tag
        if: ${{ startsWith(github.ref, 'refs/tags/dv') }}
        run: echo ROOT_TAG=$(./.github/workflows/root-tag.sh ${{env.IMAGE_TAG}}) >> $GITHUB_ENV

      - name: Calculate images full names
        run: |
          echo IMAGE_GAD=docker.pkg.github.com/$IMAGE_REPO/git-auto-deploy:$IMAGE_TAG >> $GITHUB_ENV
          echo IMAGE_GAD_CH=docker.pkg.github.com/$IMAGE_REPO/gitautodeploy-ch:$IMAGE_TAG >> $GITHUB_ENV
          echo IMAGE_GAD_CH_ROOT=docker.pkg.github.com/$IMAGE_REPO/gitautodeploy-ch:${{env.ROOT_PREFIX}}$IMAGE_TAG >> $GITHUB_ENV

      - name: Login to GitHub Packages Docker Registry
        run: |
          docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build "git-auto-deploy"
        run: |
          docker build \
              --rm \
              -f docker/image-gitautodeploy/Dockerfile \
              -t $IMAGE_GAD \
              .

      - name: Build "gitautodeploy-ch"
        run: |
          docker build \
              --rm \
              -f docker/image-gitautodeploy-ch/Dockerfile \
              -t $IMAGE_GAD_CH \
              --build-arg TAG=$IMAGE_TAG \
              --build-arg REPO=$IMAGE_REPO \
              docker/image-gitautodeploy-ch

      - name: Build ROOT based "gitautodeploy-ch"
        if: ${{'false' == env.IS_ROOT}}
        run: |
          docker build \
              --rm \
              -f docker/image-gitautodeploy-ch/Dockerfile \
              -t $IMAGE_GAD_CH_ROOT \
              --build-arg TAG=${{env.ROOT_TAG}} \
              --build-arg REPO=${{env.ROOT_REPO}} \
              docker/image-gitautodeploy-ch

      - name: Push "git-auto-deploy" to GitHub Packages
        if: ${{ env.IMAGE_PUSH == 'true' }}
        run: |
          docker push $IMAGE_GAD

      - name: Push "gitautodeploy-ch" to GitHub Packages
        if: ${{ env.IMAGE_PUSH == 'true' }}
        run: |
          docker push $IMAGE_GAD_CH

      - name: Push ROOT based "gitautodeploy-ch" to GitHub Packages
        if: ${{ env.IMAGE_PUSH == 'true' }}
        run: |
          docker push $IMAGE_GAD_CH_ROOT
